### PR TITLE
fix bundler install

### PR DESCRIPTION
**Pull request by ahorek**

### CODE REVIEW

**Comment by jeremy** [comment]
What's this fixing, @ahorek?

**Comment by ahorek** [comment]
Jruby doesn't allow you to use an older version of bundler, see
https://travis-ci.org/discourse/mini_mime/jobs/483969716

It might be a jruby's bug. I'm not sure if it should be allowed or not.

**Comment by SamSaffron** [comment]
feels mega hacky to me, @headius is there anything we need to report somewhere?

**Comment by ahorek** [comment]
according to https://github.com/bundler/bundler/issues/6932 you can't require an older bundler version if bundler 2.0+ is already installed.
any idea how to fix it in a less hacky way?

**Comment by SamSaffron** [comment]
what about simply allowing version 2 of bundler in the gemspec? Will that work?

I don't like the idea of allowing stuff lower than 1.13, but bundler 2 should work.

**Comment by SamSaffron** [comment]
Feel free to amend travis to say we don't care about failures on Ruby 2.2 and below. They are EOL releases so I do not think we should explicitly support (@jeremy  ? )  That said, the failure is a bit odd.

**Comment by jeremy** [comment]
+ dropping EOL for CI

**Comment by SamSaffron** [comment]
Looks good to me ... going to drop stuff from travis next

**Pull request merged**
