### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by SamSaffron**

### CODE REVIEW

**Review by oblakeerickson — APPROVED** [review]

**Comment by SamSaffron** [comment]
yikes I was just about to push it @casperisfine but it looks like tests are failing on main...

**Comment by casperisfine** [comment]
👀

**Comment by casperisfine** [comment]
I can repro after updating mime-types.

**Comment by casperisfine** [comment]
```
  1) Failure:
MiniMimeTest#test_full_parity_with_mime_types [/Users/byroot/src/github.com/casperisfine/mini_mime/test/mini_mime_test.rb:139]:
Expected ".ggs" to return "application/vnd.geogebra.slides", got: nil
Expected ".cjs" to return "text/javascript", got: nil
```

**Comment by casperisfine** [comment]
Caused by https://github.com/mime-types/mime-types-data/commit/02786577194203a143e421354ee74a4a53e568cb

Not sure what is best here, I can easily ignore these in the test.

**Pull request merged**
